[project]
name = "sqlwarehouse-to-lakebase-backend-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-sdk>=0.64.0",
    "debugpy>=1.8.16",
    "streamlit>=1.49.0",
]
